blank_issues_enabled: true
contact_links:
  - name: Dead Money Github Repo Discussions
    url: https://github.com/Araxiel/Dead_Money-Vicky3_Fallout/discussions
    about: Please ask and answer questions here.